CREATE DATABASE `toasterdb` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `BUSINESS_INFO` (
  `BUSINESS_NAME` varchar(30) NOT NULL,
  `ADDRESS` varchar(45) NOT NULL,
  `CITY` varchar(45) NOT NULL,
  `STATE` varchar(45) NOT NULL,
  `ZIP` varchar(7) NOT NULL,
  `SHIPMENT_BUSINESS_ID` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CUSTOMER_ORDER` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOMER_NAME` varchar(50) NOT NULL,
  `STATUS` varchar(50) DEFAULT NULL,
  `PAYMENT_CONFIRMATION_ID` varchar(37) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CUSTOMER_ORDER_LINE_ITEM` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ORDER_ID` int NOT NULL,
  `ITEM_ID` int NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_ORDER_ID` (`CUSTOMER_ORDER_ID`),
  KEY `ITEM_ID` (`ITEM_ID`),
  CONSTRAINT `CUSTOMER_ORDER_LINE_ITEM_ibfk_1` FOREIGN KEY (`CUSTOMER_ORDER_ID`) REFERENCES `CUSTOMER_ORDER` (`ID`),
  CONSTRAINT `CUSTOMER_ORDER_LINE_ITEM_ibfk_2` FOREIGN KEY (`ITEM_ID`) REFERENCES `INVENTORY` (`ITEM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `INVENTORY` (
  `ITEM_ID` int NOT NULL AUTO_INCREMENT,
  `ITEM_NAME` varchar(75) NOT NULL,
  `UNIT_PRICE` decimal(9,2) NOT NULL,
  `STOCK_QUANTITY` int NOT NULL,
  `WEIGHT` decimal(5,2) NOT NULL,
  PRIMARY KEY (`ITEM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
